# .github/workflows/deploy.yml

name: Deploy React App to Afrihost

on:
  push:
    branches:
      - release # This workflow will run whenever you push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner provided by GitHub Actions

    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: SFTP upload
        env:
          SFTP_HOST: ${{ secrets.SFTP_HOST }}
          SFTP_USERNAME: ${{ secrets.SFTP_USERNAME }}
          SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
          SFTP_PORT: ${{ secrets.SFTP_PORT }}
        run: |
          lftp -u "$SFTP_USERNAME","$SFTP_PASSWORD" sftp://"$SFTP_HOST":"${SFTP_PORT:-22}" -e "
            set net:timeout 60;
            set net:max-retries 5;
            set net:reconnect-interval-base 5;
            set net:reconnect-interval-max 20;
            mirror -R --verbose ./ ./;
            bye
          "
      - name: Install requirements in venv
        run: |
            python -m venv venv
            ./venv/bin/pip install --upgrade pip
            ./venv/bin/pip install -r requirements.txt


 
