# .github/workflows/deploy.yml

name: Deploy React App to Afrihost

on:
  push:
    branches:
      - release # This workflow will run whenever you push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner provided by GitHub Actions

    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: SFTP upload
        uses: Dylan700/sftp-upload-action@latest
        with:
          server: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: ${{ secrets.SFTP_PORT }}
          uploads: | 
            ./ => ./
      - name: Create and activate virtualenv
        run: |
              ./venv/bin/pip install -r requirements.txt

